- name: Hello World Sample
  hosts: all
  collections:
  - ansible.windows
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_shell:
         script: |
          echo "Hello World"
