- name: Hello World Sample
  hosts: all
  collections:
  - name: ansible.windows
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
         script: |
          echo "Hello World"
