- name: Run powershell script
  hosts: all 
  gather_facts: false
  collections:
  - name: community.windows
  tasks:
    - name: Run multi-lined shell commands
      ansible.windows.win_powershell: |
        $value = Test-Path -Path C:\temp
        if ($value) {
            Remove-Item -Path C:\temp -Force
        }
        New-Item -Path C:\temp -ItemType Directory
